import { Customer, Order, Coupon, CouponUsage, Review, ShippingSettings, RefundLog, Product, SiteSettings } from "@/types";

export const INITIAL_PRODUCTS_DATA: Product[] = [
  {
    id: "1",
    name: "প্রিমিয়াম ভেলভেট ক্যাট কলার (Premium Velvet Cat Collar)",
    price: 1200,
    category: "cats",
    brand: "Paws & Co.",
    description: "আপনার প্রিয় বিড়ালের জন্য অত্যন্ত নরম এবং স্টাইলিশ ভেলভেট কলার। এতে রয়েছে সেইফটি বেসবল বেল ও অ্যাডজাস্টেবল লক।",
    imageUrl: "/collar.png",
    stock: 15,
    lowStockThreshold: 5,
    costPrice: 650,
    variants: [
      { id: "v-red", color: "Forest Green", size: "Standard", stock: 8 },
      { id: "v-blue", color: "Royal Blue", size: "Standard", stock: 7 },
    ],
  },
  {
    id: "cat_litter_premium",
    name: "প্রিমিয়াম সিলিকা ক্যাট লিটার - ৫ লিটার (Premium Silica Litter)",
    price: 850,
    category: "cats",
    brand: "FreshPaws",
    description: "উচ্চ শোষণ ক্ষমতাসম্পন্ন অ্যান্টি-ব্যাকটেরিয়াল সিলিকা ক্যাট লিটার। দুর্গন্ধ মুক্ত রাখতে অত্যন্ত কার্যকরী।",
    imageUrl: "/litter.png",
    stock: 24,
    lowStockThreshold: 10,
    costPrice: 420,
    variants: [
      { id: "v-5l", size: "5 Liter", stock: 15 },
      { id: "v-10l", size: "10 Liter", stock: 9 },
    ],
  },
  {
    id: "leather_dog_leash",
    name: "জেনুইন লেদার ডগ লিশ (Genuine Leather Dog Leash)",
    price: 1850,
    category: "dogs",
    brand: "Barkmaster",
    description: "টেকসই খাঁটি চামড়ার তৈরি মজবুত ডগ লিশ। বড় ও মাঝারি কুকুরের জন্য পারফেক্ট গ্রিপ ও কমফোর্ট।",
    imageUrl: "/leash.png",
    stock: 8,
    lowStockThreshold: 3,
    costPrice: 950,
    variants: [
      { id: "v-brown", color: "Classic Brown", size: "5ft", stock: 5 },
      { id: "v-black", color: "Matte Black", size: "5ft", stock: 3 },
    ],
  },
  {
    id: "2",
    name: "অর্গানিক স্যামন ও গ্রেইন-ফ্রি ক্যাট ফুড (Organic Salmon Cat Food)",
    price: 2400,
    category: "cats",
    brand: "Feline Harvest",
    description: "প্রাকৃতিক সামুদ্রিক স্যামন মাছ এবং তাজা শাকসবজির পুষ্টিকর সমন্বয়। ১০০% গ্রেইন-ফ্রি স্বাস্থ্যকর বিড়ালের খাবার।",
    imageUrl: "/cat_food.jpg",
    stock: 18,
    lowStockThreshold: 5,
    costPrice: 1400,
  },
  {
    id: "dog_shampoo",
    name: "অর্গানিক সুদিং ডগ শ্যাম্পু (Organic Soothing Dog Shampoo)",
    price: 950,
    category: "dogs",
    brand: "Paws & Calm",
    description: "ল্যাভেন্ডার ও ক্যামোমাইল এক্সট্রাক্ট সমৃদ্ধ অ্যান্টি-অ্যালার্জিক হাইপোঅ্যালার্জেনিক কুকুরের শ্যাম্পু।",
    imageUrl: "/dog_shampoo.jpg",
    stock: 30,
    lowStockThreshold: 8,
    costPrice: 480,
  },
  {
    id: "dog_chew_toy",
    name: "ডিউরেবল রাবার ডগ চিউ টয় (Durable Rubber Dog Chew Toy)",
    price: 650,
    category: "dogs",
    brand: "Barkwell",
    description: "১০০% প্রাকৃতিক বিষাক্তহীন রাবারের তৈরি টেকসই দাঁতের এক্সারসাইজ চিউ টয়।",
    imageUrl: "/dog_chew_toy.jpg",
    stock: 45,
    lowStockThreshold: 10,
    costPrice: 280,
  },
  {
    id: "bird_cage_large",
    name: "স্টেইনলেস স্টিল বার্ড কেজ (Stainless Steel Bird Cage)",
    price: 3800,
    category: "birds",
    brand: "FeatherHome",
    description: "পাখির আনন্দের জন্য তৈরি প্রশস্ত ও নিরাপদ স্টেইনলেস স্টিল মেটাল খাঁচা। ফিডার ও স্ট্যান্ড সহ।",
    imageUrl: "/bird_cage.jpg",
    stock: 6,
    lowStockThreshold: 2,
    costPrice: 2200,
  },
];

export const INITIAL_CUSTOMERS_DATA: Customer[] = [
  {
    id: "cust-1",
    name: "আরিফ রহমান",
    email: "arif@example.com",
    phone: "01712345678",
    shippingAddresses: ["গুলশান-১, ঢাকা", "বনানী, ব্লক-ডি, ঢাকা"],
    totalOrders: 2,
    totalSpent: 4160,
    signupDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    emailVerified: true,
    phoneVerified: true,
    lastLoginDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "cust-2",
    name: "তাহমিদ হাসান",
    email: "tahmid@example.com",
    phone: "01898765432",
    shippingAddresses: ["মিরপুর-১০, ঢাকা"],
    totalOrders: 1,
    totalSpent: 1160,
    signupDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    emailVerified: true,
    phoneVerified: false,
    lastLoginDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_ORDERS_DATA: Order[] = [
  {
    id: "ORD-8492",
    customerName: "আরিফ রহমান",
    customerPhone: "01712345678",
    customerAddress: "গুলশান-১, ব্লক-বি, রোড-৭, বাসা-১২, ঢাকা",
    items: [
      { id: "1", name: "প্রিমিয়াম ভেলভেট ক্যাট কলার (Forest Green)", price: 1200, quantity: 1, selectedColor: "Forest Green" },
      { id: "cat_litter_premium", name: "প্রিমিয়াম সিলিকা ক্যাট লিটার (৫ লিটার)", price: 850, quantity: 2, selectedSize: "5 Liter" },
    ],
    subtotal: 2900,
    shippingFee: 60,
    grandTotal: 2960,
    paymentMethod: "cod",
    paymentStatus: "Unpaid",
    status: "Received",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-8491",
    customerName: "তাহমিদ হাসান",
    customerPhone: "01898765432",
    customerAddress: "মিরপুর-১০, রোড-২, বাসা-৪, ঢাকা",
    items: [
      { id: "dog_shampoo", name: "অর্গানিক সুদিং ডগ শ্যাম্পু", price: 950, quantity: 1 },
    ],
    subtotal: 950,
    shippingFee: 60,
    grandTotal: 1010,
    paymentMethod: "bkash",
    paymentStatus: "Paid",
    transactionId: "BKASH_998877665",
    courierPartner: "Pathao",
    trackingNumber: "PTH-9928341",
    status: "Shipped",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_COUPONS_DATA: Coupon[] = [
  {
    id: "c-1",
    code: "PAWS10",
    discountType: "percentage",
    discountValue: 10,
    minOrderAmount: 1000,
    maxDiscountCap: 300,
    startDate: "2026-01-01T00:00:00.000Z",
    endDate: "2026-12-31T23:59:59.000Z",
    totalUsageLimit: 500,
    perUserUsageLimit: 2,
    usedCount: 42,
    applicableOn: "all",
    isActive: true,
    createdAt: new Date("2026-01-01T00:00:00.000Z").toISOString(),
  },
  {
    id: "c-2",
    code: "FLAT200",
    discountType: "fixed",
    discountValue: 200,
    minOrderAmount: 1500,
    startDate: "2026-06-01T00:00:00.000Z",
    endDate: "2026-08-31T23:59:59.000Z",
    totalUsageLimit: 100,
    perUserUsageLimit: 1,
    usedCount: 18,
    applicableOn: "all",
    isActive: true,
    createdAt: new Date("2026-06-01T00:00:00.000Z").toISOString(),
  },
];

export const INITIAL_REVIEWS_DATA: Review[] = [
  {
    id: "rev-1",
    productId: "1",
    productName: "প্রিমিয়াম ভেলভেট ক্যাট কলার",
    customerName: "আরিফ রহমান",
    customerPhone: "01712345678",
    rating: 5,
    comment: "অসাধারণ কোয়ালিটি! আমার বিড়ালের গলায় দেখতে খুবই সুন্দর লাগছে। বেল এর সাউন্ডও খুব সুইট।",
    status: "approved",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rev-2",
    productId: "cat_litter_premium",
    productName: "প্রিমিয়াম সিলিকা ক্যাট লিটার",
    customerName: "সাদিয়া ইসলাম",
    customerPhone: "01511223344",
    rating: 4,
    comment: "লিটারটা সত্যিই খুব ভালো, স্মেল কন্ট্রোল চমৎকার করে। দামটা আর একটু কম হলে ভালো হতো।",
    status: "approved",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_SHIPPING_SETTINGS_DATA: ShippingSettings = {
  insideDhakaCharge: 60,
  outsideDhakaCharge: 120,
  subAreaCharge: 100,
  freeShippingThreshold: 3000,
};

export const INITIAL_SITE_SETTINGS_DATA: SiteSettings = {
  heroBannerUrl: "/hero.png",
  heroBannerTitle: "বাংলাদেশের ১ নম্বর বিশ্বস্ত পেট শপ",
  heroBannerSubtitle: "আপনার পোষ্য বিড়াল, কুকুর ও পাখির জন্য সেরা পণ্যসমূহ সরাসরি পৌঁছে যাবে আপনার ঘরে।",
  contactPhone: "01700-000000",
  contactEmail: "support@paws.co",
  contactAddress: "গুলশান-১, ঢাকা, বাংলাদেশ",
  contactWhatsapp: "8801700000000",
  socialFacebook: "https://facebook.com/pawscobd",
  socialInstagram: "https://instagram.com/pawscobd",
  seoHomeTitle: "Paws & Co. | Premium Pet Accessories in Bangladesh",
  seoHomeDescription: "Buy premium cat collars, silica litters, organic foods, and pet supplies in Bangladesh.",
  seoProductsTitle: "Pet Products Catalog | Paws & Co.",
  seoProductsDescription: "Explore high quality pet accessories and foods with fast nationwide shipping.",
  featuredProductIds: ["1", "cat_litter_premium", "leather_dog_leash"],
  trendingProductIds: ["2", "dog_shampoo", "dog_chew_toy"],
};
